spring:
  application:
    name: secure-url-shortener

  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jackson:
    time-zone: UTC
    default-property-inclusion: non_null

server:
  port: "${PORT:8081}"
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: ${JWT_SECRET:dev-only-secret-change-me-32-bytes-min}
    expiration-ms: 3600000
    refresh-expiration-ms: 604800000

  encryption:
    secret-key: ${ENCRYPTION_SECRET_KEY:dev-only-encryption-key-32bytes!}

  short-link:
    code-length: 8
    base-redirect-url: ${BASE_REDIRECT_URL:http://localhost:5173/r}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.adi.urlshortener: INFO
    org.springframework.security: WARN